// foodstore-store/src/routes/admin/analytics/+page.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { formatCurrency } from '$lib/utils/index.ts';
	import { signalRService } from '$lib/services/signalr.ts';
	import { AnalyticsState } from './analytics.svelte.js';
	import Icon from '$lib/components/ui/Icon.svelte';

	const vm = new AnalyticsState();

	// UI Local State - only canvas refs
	let revenueChartDiv: HTMLDivElement = $state()!;
	let ordersChartDiv: HTMLDivElement = $state()!;
	let forecastChartDiv: HTMLDivElement = $state()!;
	let sourceChartDiv: HTMLDivElement = $state()!;

	// Reactive: update dates when dateRange changes

	// Re-initialize charts when data changes
	$effect(() => {
		if (!vm.loading && vm.stats) {
			setTimeout(() => {
				vm.initCharts({
					revenue: revenueChartDiv,
					orders: ordersChartDiv,
					forecast: forecastChartDiv,
					source: sourceChartDiv
				});
			}, 100);
		}
	});

	onMount(async () => {
		vm.updateDatesFromRange('7days');
		await vm.loadData();

		// Start SignalR connection
		const token = localStorage.getItem('token');
		if (token) {
			await signalRService.startConnection(token);
			signalRService.on('ReceiveOrderUpdate', handleOrderUpdate);
		}
	});

	onDestroy(() => {
		signalRService.off('ReceiveOrderUpdate', handleOrderUpdate);
	});

	function handleOrderUpdate(data: any) {
		vm.handleOrderUpdate(data);
	}

	async function onFilterApply() {
		await vm.loadData();
	}
</script>

<svelte:head>
	<title>Thống Kê & Dự Báo - Admin Foodstore</title>
</svelte:head>

<div class="space-y-6 p-6">
	<div class="flex items-center justify-between">
		<!-- Filters -->
		<div
			class="flex items-center gap-3 rounded-2xl border border-gray-100 bg-white p-1.5 shadow-sm"
		>
			<select
				bind:value={vm.dateRange}
				onchange={() => vm.dateRange !== 'custom' && vm.updateDatesFromRange(vm.dateRange)}
				class="cursor-pointer rounded-xl border-transparent bg-transparent px-4 py-2 text-sm font-bold text-gray-700 transition-colors hover:bg-gray-50 focus:ring-0"
			>
				<option value="7days">7 ngày qua</option>
				<option value="30days">30 ngày qua</option>
				<option value="thisMonth">Tháng này</option>
				<option value="last3Months">3 tháng qua</option>
				<option value="custom">Tùy chỉnh</option>
			</select>

			{#if vm.dateRange === 'custom'}
				<div class="flex items-center gap-2 border-l border-gray-100 px-2">
					<input
						type="date"
						bind:value={vm.fromDate}
						class="rounded-lg border-gray-100 py-1 text-xs font-medium"
					/>
					<span class="text-gray-300">/</span>
					<input
						type="date"
						bind:value={vm.toDate}
						class="rounded-lg border-gray-100 py-1 text-xs font-medium"
					/>
					<button
						onclick={onFilterApply}
						class="rounded-lg bg-indigo-600 px-3 py-1 text-xs font-bold text-white transition-colors hover:bg-indigo-700"
					>
						Lọc
					</button>
				</div>
			{/if}
		</div>
	</div>

	{#if vm.loading}
		<div class="flex h-64 items-center justify-center">
			<div class="h-12 w-12 animate-spin rounded-full border-b-2 border-indigo-600"></div>
		</div>
	{:else if vm.error}
		<div class="relative rounded border border-red-200 bg-red-50 px-4 py-3 text-red-700">
			{vm.error}
		</div>
	{:else if vm.stats}
		<!-- Key Metrics -->
		<div class="grid grid-cols-1 gap-6 md:grid-cols-3">
			<div
				class="group rounded-2xl border border-gray-100 bg-white p-6 shadow-sm transition-all hover:shadow-md"
			>
				<p class="text-[10px] font-bold tracking-widest text-gray-400 uppercase">Tổng doanh thu</p>
				<p
					class="mt-2 origin-left text-3xl font-black text-indigo-600 transition-transform group-hover:scale-105"
				>
					{formatCurrency(vm.stats.totalRevenue)}
				</p>
			</div>
			<div
				class="group rounded-2xl border border-gray-100 bg-white p-6 shadow-sm transition-all hover:shadow-md"
			>
				<p class="text-[10px] font-bold tracking-widest text-gray-400 uppercase">Tổng thuế VAT</p>
				<p
					class="mt-2 origin-left text-3xl font-black text-emerald-600 transition-transform group-hover:scale-105"
				>
					{formatCurrency(vm.stats.totalVat || 0)}
				</p>
			</div>
			<div
				class="group rounded-2xl border border-gray-100 bg-white p-6 shadow-sm transition-all hover:shadow-md"
			>
				<p class="text-[10px] font-bold tracking-widest text-gray-400 uppercase">Tổng đơn hàng</p>
				<p
					class="mt-2 origin-left text-3xl font-black text-orange-600 transition-transform group-hover:scale-105"
				>
					{vm.stats.totalOrders}
				</p>
			</div>
		</div>

		<!-- Charts Grid -->
		<div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
			<!-- Revenue Chart -->
			<div
				class="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm transition-all hover:shadow-md"
			>
				<h3 class="mb-6 text-xs font-bold tracking-widest text-gray-400 uppercase">
					Xu hướng doanh thu
				</h3>
				<div bind:this={revenueChartDiv} class="h-72"></div>
			</div>

			<!-- Orders Chart -->
			<div
				class="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm transition-all hover:shadow-md"
			>
				<h3 class="mb-6 text-xs font-bold tracking-widest text-gray-400 uppercase">
					Số lượng đơn hàng
				</h3>
				<div bind:this={ordersChartDiv} class="h-72"></div>
			</div>
		</div>

		<!-- Service Analysis Section -->
		<div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
			<!-- Service Type Chart -->
			<div
				class="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm transition-all hover:shadow-md"
			>
				<h3 class="mb-6 text-xs font-bold tracking-widest text-gray-400 uppercase">
					Phân bố Nguồn đơn
				</h3>
				<div bind:this={sourceChartDiv} class="h-72"></div>
			</div>

			<!-- Strategic Insight -->
			<div
				class="group relative overflow-hidden rounded-2xl border border-indigo-100 bg-indigo-50/30 p-8 shadow-sm lg:col-span-2"
			>
				<div
					class="absolute -top-16 -right-16 h-48 w-48 rounded-full bg-indigo-100/50 blur-3xl transition-transform group-hover:scale-125"
				></div>

				<div class="relative flex flex-col gap-6 md:flex-row">
					<div
						class="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 shadow-xl shadow-indigo-200"
					>
						<Icon name="tabler:bulb" class="h-7 w-7 text-white" />
					</div>
					<div>
						<h3 class="text-xl font-black text-indigo-900">AI Strategic Insight</h3>
						<div
							class="prose prose-sm mt-4 max-w-none leading-relaxed text-indigo-900/80 prose-indigo"
						>
							{#if vm.forecast?.recommendation}
								<p class="text-base font-medium">
									{vm.forecast.recommendation}
								</p>
							{:else}
								<div class="flex items-center gap-3 py-2 text-indigo-400 italic">
									<div
										class="h-4 w-4 animate-spin rounded-full border-2 border-indigo-400 border-t-transparent"
									></div>
									Hệ thống đang phân tích xu hướng...
								</div>
							{/if}
						</div>
						<button
							class="mt-6 flex items-center gap-2 text-sm font-extrabold text-indigo-600 transition-colors hover:text-indigo-800"
						>
							<span>Khám phá báo cáo chi tiết</span>
							<Icon name="tabler:arrow-right" class="h-4 w-4" />
						</button>
					</div>
				</div>
			</div>
		</div>

		<!-- AI Forecast Section -->
		<div
			class="rounded-xl border border-indigo-100 bg-gradient-to-br from-indigo-50 to-white p-6 shadow-sm"
		>
			<div class="mb-6 flex items-center justify-between">
				<div class="flex items-center gap-3">
					<div class="rounded-lg bg-indigo-600 p-2">
						<Icon name="tabler:wand" class="h-6 w-6 text-white" />
					</div>
					<div>
						<h3 class="text-lg font-bold text-gray-900">Dự báo doanh thu (AI Powered)</h3>
						<p class="text-sm text-gray-600">
							Sử dụng Machine Learning để dự đoán doanh thu 7 ngày tới
						</p>
					</div>
				</div>
				<div
					class="rounded border border-indigo-200 bg-white px-2 py-1 font-mono text-xs text-indigo-700"
				>
					Model: SSA-Forecasting
				</div>
			</div>

			<div class="rounded-lg border border-indigo-50 bg-white p-4 shadow-sm">
				<div bind:this={forecastChartDiv} class="h-80"></div>
			</div>

			<div class="mt-4 text-center text-sm text-gray-500 italic">
				* Dự báo chỉ mang tính chất tham khảo dựa trên dữ liệu lịch sử.
			</div>
		</div>

		<!-- Top Items Table -->
		<div class="overflow-hidden rounded-xl border border-gray-100 bg-white shadow-sm">
			<div class="border-b border-gray-100 px-6 py-4">
				<h3 class="text-lg font-semibold text-gray-900">Top món bán chạy (Giai đoạn này)</h3>
			</div>
			<div class="overflow-x-auto">
				<table class="min-w-full divide-y divide-gray-200">
					<thead class="bg-gray-50">
						<tr>
							<th
								class="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase"
								>Tên món</th
							>
							<th
								class="px-6 py-3 text-right text-xs font-medium tracking-wider text-gray-500 uppercase"
								>Số lượng bán</th
							>
							<th
								class="px-6 py-3 text-right text-xs font-medium tracking-wider text-gray-500 uppercase"
								>Tỷ trọng</th
							>
						</tr>
					</thead>
					<tbody class="divide-y divide-gray-200 bg-white">
						{#each vm.stats.topItems as item (item.name)}
							<tr class="hover:bg-gray-50">
								<td class="px-6 py-4 text-sm font-medium whitespace-nowrap text-gray-900"
									>{item.name}</td
								>
								<td class="px-6 py-4 text-right text-sm font-bold whitespace-nowrap text-gray-900"
									>{item.sold}</td
								>
								<td class="px-6 py-4 text-right text-sm whitespace-nowrap text-gray-500">
									<div
										class="mr-2 ml-auto inline-block h-2.5 w-24 rounded-full bg-gray-200 align-middle"
									>
										<div
											class="h-2.5 rounded-full bg-indigo-600"
											style="width: {(item.sold /
												// eslint-disable-next-line @typescript-eslint/no-explicit-any
												Math.max(...vm.stats.topItems.map((i: any) => i.sold))) *
												100}%"
										></div>
									</div>
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		</div>

		<!-- Popular Combos Table -->
		<div class="overflow-hidden rounded-xl border border-gray-100 bg-white shadow-sm">
			<div class="border-b border-gray-100 px-6 py-4">
				<h3 class="text-lg font-semibold text-gray-900">Combo bán chạy (Giai đoạn này)</h3>
			</div>
			<div class="overflow-x-auto">
				<table class="min-w-full divide-y divide-gray-200">
					<thead class="bg-gray-50">
						<tr>
							<th
								class="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase"
								>Tên Combo</th
							>
							<th
								class="px-6 py-3 text-right text-xs font-medium tracking-wider text-gray-500 uppercase"
								>Số lượng bán</th
							>
							<th
								class="px-6 py-3 text-right text-xs font-medium tracking-wider text-gray-500 uppercase"
								>Tỷ trọng</th
							>
						</tr>
					</thead>
					<tbody class="divide-y divide-gray-200 bg-white">
						{#if vm.stats.popularCombos && vm.stats.popularCombos.length > 0}
							{#each vm.stats.popularCombos as item (item.name)}
								<tr class="hover:bg-gray-50">
									<td class="px-6 py-4 text-sm font-medium whitespace-nowrap text-gray-900"
										>{item.name}</td
									>
									<td class="px-6 py-4 text-right text-sm font-bold whitespace-nowrap text-gray-900"
										>{item.sold}</td
									>
									<td class="px-6 py-4 text-right text-sm whitespace-nowrap text-gray-500">
										<div
											class="mr-2 ml-auto inline-block h-2.5 w-24 rounded-full bg-gray-200 align-middle"
										>
											<div
												class="h-2.5 rounded-full bg-purple-600"
												style="width: {(item.sold /
													// eslint-disable-next-line @typescript-eslint/no-explicit-any
													Math.max(...vm.stats.popularCombos.map((i: any) => i.sold))) *
													100}%"
											></div>
										</div>
									</td>
								</tr>
							{/each}
						{:else}
							<tr>
								<td colspan="3" class="px-6 py-4 text-center text-sm text-gray-500"
									>Chưa có dữ liệu combo</td
								>
							</tr>
						{/if}
					</tbody>
				</table>
			</div>
		</div>
		<!-- AI Combo Recommendations -->
		<div
			class="rounded-xl border border-purple-100 bg-gradient-to-br from-purple-50 to-white p-6 shadow-sm"
		>
			<div class="mb-6 flex items-center justify-between">
				<div class="flex items-center gap-3">
					<div class="rounded-lg bg-purple-600 p-2">
						<Icon name="tabler:wand" class="h-6 w-6 text-white" />
					</div>
					<div>
						<h3 class="text-lg font-bold text-gray-900">Gợi ý Combo (AI Recommendation)</h3>
						<p class="text-sm text-gray-600">
							Các món thường được gọi cùng nhau - Cơ hội tạo Combo mới
						</p>
					</div>
				</div>
			</div>

			{#if vm.recommendations && vm.recommendations.length > 0}
				<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
					{#each vm.recommendations as rec, i (i)}
						<div
							class="rounded-lg border border-purple-100 bg-white p-4 shadow-sm transition-shadow hover:shadow-md"
						>
							<div class="mb-3 flex items-center gap-2">
								<span class="rounded bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700"
									>{rec.item1Name}</span
								>
								<span class="text-gray-400">+</span>
								<span class="rounded bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700"
									>{rec.item2Name}</span
								>
							</div>
							<div class="mb-2 flex items-end justify-between">
								<div>
									<p class="text-xs text-gray-500 line-through">
										{formatCurrency(rec.totalOriginalPrice)}
									</p>
									<p class="text-lg font-bold text-purple-600">
										{formatCurrency(rec.suggestedPrice)}
									</p>
								</div>
								<div class="text-right">
									<span
										class="rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-600"
										>Tiết kiệm 10%</span
									>
								</div>
							</div>
							<p class="mt-2 border-t border-gray-50 pt-2 text-xs text-gray-500">
								{rec.reason}
							</p>
						</div>
					{/each}
				</div>
			{:else}
				<p class="py-8 text-center text-gray-500">Chưa đủ dữ liệu để gợi ý combo.</p>
			{/if}
		</div>
	{/if}
</div>

// foodstore-admin/src/app/admin/food/analytics/page.tsx
"use client"

import * as React from "react"
import { BarChart3, ShoppingCart, Receipt, Wand2 } from "lucide-react"
import { toast } from "sonner"
import {
  Bar, BarChart, CartesianGrid, Line, LineChart,
  ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "@/components/ui/dynamic-charts"

import { Breadcrumb, BreadcrumbItem, BreadcrumbList, BreadcrumbPage } from "@/components/ui/breadcrumb"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { NativeSelect } from "@/components/ui/native-select"
import { Separator } from "@/components/ui/separator"
import { SidebarTrigger } from "@/components/ui/sidebar"
import { dashboardService } from "@/lib/services/dashboard-service"
import { formatCurrency } from "@/lib/utils"
import type { Analytics, Forecast, Recommendation } from "@/lib/types"

export default function AnalyticsPage() {
  const [dateRange, setDateRange] = React.useState("7days")
  const [fromDate, setFromDate] = React.useState("")
  const [toDate, setToDate] = React.useState("")
  const [analytics, setAnalytics] = React.useState<Analytics | null>(null)
  const [forecast, setForecast] = React.useState<Forecast | null>(null)
  const [recommendations, setRecommendations] = React.useState<Recommendation[]>([])
  const [loading, setLoading] = React.useState(true)

  const updateDatesFromRange = (range: string) => {
    const now = new Date()
    const to = now.toISOString().split("T")[0]
    let from: string
    switch (range) {
      case "7days": from = new Date(now.getTime() - 7 * 86400000).toISOString().split("T")[0]; break
      case "30days": from = new Date(now.getTime() - 30 * 86400000).toISOString().split("T")[0]; break
      case "thisMonth": from = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split("T")[0]; break
      case "last3Months": from = new Date(now.getTime() - 90 * 86400000).toISOString().split("T")[0]; break
      default: from = ""
    }
    setFromDate(from); setToDate(to)
  }

  const loadData = React.useCallback(async () => {
    setLoading(true)
    try {
      const [a, f, r] = await Promise.all([
        dashboardService.getAnalytics(fromDate || undefined, toDate || undefined, "day").catch(() => null),
        dashboardService.getForecast(7).catch(() => null),
        dashboardService.getRecommendations().catch(() => []),
      ])
      setAnalytics(a); setForecast(f); setRecommendations(r)
    } catch { toast.error("Không thể tải dữ liệu") }
    finally { setLoading(false) }
  }, [fromDate, toDate])

  React.useEffect(() => { updateDatesFromRange(dateRange) }, [dateRange])
  React.useEffect(() => { if (fromDate || dateRange !== "custom") loadData() }, [fromDate, dateRange, loadData])

  return (
    <>
      <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
        <div className="flex items-center gap-2 px-4">
          <SidebarTrigger className="-ml-1" />
          <Separator orientation="vertical" className="mr-2 h-4" />
          <Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbPage>Thống kê & Dự báo</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb>
        </div>
      </header>
      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
        <div className="flex items-center gap-3 rounded-xl border bg-card p-2 shadow-sm">
          <NativeSelect className="w-fit border-0 bg-transparent font-medium" value={dateRange} onChange={(e) => { const v = e.target.value; setDateRange(v); if (v !== "custom") updateDatesFromRange(v) }}>
            <option value="7days">7 ngày qua</option>
            <option value="30days">30 ngày qua</option>
            <option value="thisMonth">Tháng này</option>
            <option value="last3Months">3 tháng qua</option>
            <option value="custom">Tùy chỉnh</option>
          </NativeSelect>
          {dateRange === "custom" && (
            <div className="flex items-center gap-2 border-l pl-3">
              <Input type="date" className="h-8 w-fit" value={fromDate} onChange={(e) => setFromDate(e.target.value)} />
              <span className="text-muted-foreground">→</span>
              <Input type="date" className="h-8 w-fit" value={toDate} onChange={(e) => setToDate(e.target.value)} />
              <Button size="sm" onClick={loadData}>Lọc</Button>
            </div>
          )}
        </div>

        {loading ? (
          <div className="grid gap-4 md:grid-cols-3">
            {Array.from({ length: 3 }).map((_, i) => (
              <Card key={i}><CardHeader className="pb-2"><div className="h-4 w-28 animate-pulse rounded bg-muted" /></CardHeader><CardContent><div className="h-8 w-36 animate-pulse rounded bg-muted" /></CardContent></Card>
            ))}
          </div>
        ) : analytics ? (
          <>
            <div className="grid gap-4 md:grid-cols-3">
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <CardTitle className="text-sm font-medium">Tổng doanh thu</CardTitle>
                  <BarChart3 className="size-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold text-indigo-600">{formatCurrency(analytics.totalRevenue)}</div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <CardTitle className="text-sm font-medium">Thuế VAT</CardTitle>
                  <Receipt className="size-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold text-emerald-600">{formatCurrency(analytics.totalVat)}</div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <CardTitle className="text-sm font-medium">Tổng đơn hàng</CardTitle>
                  <ShoppingCart className="size-4 text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold text-orange-600">{analytics.totalOrders}</div>
                </CardContent>
              </Card>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <Card>
                <CardHeader><CardTitle>Xu hướng doanh thu</CardTitle></CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={280}>
                    <BarChart data={analytics.revenueChart}>
                      <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                      <XAxis dataKey="label" tick={{ fontSize: 11 }} />
                      <YAxis tick={{ fontSize: 11 }} tickFormatter={(v) => `${(v / 1000).toFixed(0)}k`} />
                      <Tooltip formatter={(v) => formatCurrency(Number(v))} />
                      <Bar dataKey="value" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </CardContent>
              </Card>
              <Card>
                <CardHeader><CardTitle>Số lượng đơn hàng</CardTitle></CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={280}>
                    <BarChart data={analytics.ordersChart}>
                      <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                      <XAxis dataKey="label" tick={{ fontSize: 11 }} />
                      <YAxis tick={{ fontSize: 11 }} />
                      <Tooltip />
                      <Bar dataKey="value" fill="#10b981" radius={[4, 4, 0, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </CardContent>
              </Card>
            </div>

            {forecast && forecast.forecasts.length > 0 && (
              <Card className="border-indigo-200 bg-gradient-to-br from-indigo-50/50 to-background">
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="rounded-lg bg-indigo-600 p-2">
                        <Wand2 className="size-5 text-white" />
                      </div>
                      <div>
                        <CardTitle>Dự báo doanh thu (AI Powered)</CardTitle>
                        <CardDescription>Machine Learning dự đoán 7 ngày tới</CardDescription>
                      </div>
                    </div>
                    <div className="rounded border border-indigo-200 bg-card px-2 py-1 font-mono text-xs text-indigo-700">SSA-Forecasting</div>
                  </div>
                </CardHeader>
                <CardContent>
                  <ResponsiveContainer width="100%" height={280}>
                    <LineChart data={forecast.forecasts}>
                      <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                      <XAxis dataKey="date" tick={{ fontSize: 11 }} tickFormatter={(v) => new Date(v).toLocaleDateString("vi-VN", { day: "numeric", month: "numeric" })} />
                      <YAxis tick={{ fontSize: 11 }} tickFormatter={(v) => `${(v / 1000).toFixed(0)}k`} />
                      <Tooltip formatter={(v) => formatCurrency(Number(v))} labelFormatter={(l) => new Date(String(l)).toLocaleDateString("vi-VN")} />
                      <Line type="monotone" dataKey="revenue" stroke="#6366f1" strokeWidth={2} dot={{ r: 3, fill: "#6366f1" }} />
                    </LineChart>
                  </ResponsiveContainer>
                  <p className="mt-2 text-center text-xs italic text-muted-foreground">* Dự báo mang tính tham khảo dựa trên dữ liệu lịch sử.</p>
                </CardContent>
              </Card>
            )}

            <div className="grid gap-4 md:grid-cols-2">
              <Card>
                <CardHeader><CardTitle>Top món bán chạy</CardTitle></CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {analytics.topItems.map((item, i) => (
                      <div key={item.name} className="flex items-center gap-3">
                        <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-medium">{i + 1}</span>
                        <div className="flex-1">
                          <p className="text-sm font-medium">{item.name}</p>
                          <div className="h-2 w-full overflow-hidden rounded-full bg-muted">
                            <div className="h-full rounded-full bg-primary" style={{ width: `${Math.min(100, (item.sold / Math.max(...analytics.topItems.map((t) => t.sold))) * 100)}%` }} />
                          </div>
                        </div>
                        <span className="text-sm font-medium">{item.sold}</span>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader><CardTitle>Combo bán chạy</CardTitle></CardHeader>
                <CardContent>
                  {analytics.popularCombos.length > 0 ? (
                    <div className="space-y-3">
                      {analytics.popularCombos.map((item, i) => (
                        <div key={item.name} className="flex items-center gap-3">
                          <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-medium">{i + 1}</span>
                          <div className="flex-1">
                            <p className="text-sm font-medium">{item.name}</p>
                            <div className="flex items-center gap-2 text-xs text-muted-foreground">
                              <span>{item.quantity} đã bán</span>
                              <span>•</span>
                              <span>{formatCurrency(item.revenue)}</span>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <p className="py-8 text-center text-muted-foreground">Chưa có dữ liệu combo</p>
                  )}
                </CardContent>
              </Card>
            </div>

            {recommendations.length > 0 && (
              <Card className="border-purple-200 bg-gradient-to-br from-purple-50/50 to-background">
                <CardHeader>
                  <div className="flex items-center gap-3">
                    <div className="rounded-lg bg-purple-600 p-2">
                      <Wand2 className="size-5 text-white" />
                    </div>
                    <div>
                      <CardTitle>Gợi ý Combo (AI Recommendation)</CardTitle>
                      <CardDescription>Các món thường đi cùng nhau - Cơ hội tạo Combo mới</CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                    {recommendations.map((rec, i) => (
                      <div key={i} className="rounded-lg border border-purple-100 bg-card p-4 shadow-sm">
                        <div className="mb-3 flex items-center gap-2">
                          <span className="rounded bg-muted px-2 py-1 text-xs font-medium">{rec.item1Name}</span>
                          <span className="text-muted-foreground">+</span>
                          <span className="rounded bg-muted px-2 py-1 text-xs font-medium">{rec.item2Name}</span>
                        </div>
                        <div className="mb-2 flex items-end justify-between">
                          <div>
                            <p className="text-xs text-muted-foreground line-through">{formatCurrency(rec.totalOriginalPrice)}</p>
                            <p className="text-lg font-bold text-purple-600">{formatCurrency(rec.suggestedPrice)}</p>
                          </div>
                          <span className="rounded-full bg-green-50 px-2 py-1 text-xs font-medium text-green-600">Tiết kiệm 10%</span>
                        </div>
                        <p className="mt-2 border-t pt-2 text-xs text-muted-foreground">{rec.reason}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}
          </>
        ) : (
          <div className="flex h-64 items-center justify-center text-muted-foreground">Không có dữ liệu</div>
        )}
      </div>
    </>
  )
}
