// ChipmeoPOS/src/routes/admin/role-permissions/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Button from '$lib/components/Button.svelte';
	import Card from '$lib/components/Card.svelte';
	import { RolePermissionsState } from './role-permissions.svelte.js';

	const vm = new RolePermissionsState();

	onMount(() => {
		vm.init();
	});
</script>

<svelte:head>
	<title>Quản lý phân quyền - Admin</title>
</svelte:head>

<div class="p-6">
	<div class="mb-6">
		<h1 class="text-2xl font-bold text-gray-900">Quản lý phân quyền</h1>
		<p class="text-gray-600">Gán quyền truy cập cho các vai trò trong hệ thống</p>
	</div>

	{#if vm.loading}
		<div class="py-12 text-center">
			<div
				class="inline-block h-12 w-12 animate-spin rounded-full border-b-2 border-indigo-600"
			></div>
		</div>
	{:else}
		<div class="grid grid-cols-1 gap-6 lg:grid-cols-[280px_1fr]">
			<!-- Left Sidebar: Role List -->
			<Card>
				<h2 class="mb-4 text-lg font-semibold text-gray-800">Vai trò</h2>
				<div class="space-y-3">
					{#each vm.roles as role (role.id)}
						<button
							class="w-full rounded-lg border-2 p-3 text-left transition-all duration-200 {vm.selectedRoleId ===
							role.id
								? 'border-indigo-500 bg-indigo-50'
								: 'border-gray-100 hover:border-indigo-200 hover:bg-gray-50'}"
							onclick={() => vm.selectRole(role.id)}
						>
							<div class="mb-1 font-medium text-gray-900">{role.name}</div>
							<div class="text-sm text-gray-500">{role.description}</div>
						</button>
					{/each}
				</div>
			</Card>

			<!-- Main Area: Permission Matrix -->
			{#if vm.selectedRole}
				<div class="space-y-6">
					<!-- Header & Actions -->
					<Card>
						<div class="flex items-center justify-between">
							<div>
								<h2 class="text-xl font-bold text-gray-900">Quyền của {vm.selectedRole.name}</h2>
								<div class="mt-1 text-sm text-gray-500">
									Đang chọn {vm.rolePermissionIds.length} quyền
								</div>
							</div>
							<Button variant="primary" onclick={() => vm.savePermissions()} disabled={vm.saving}>
								{vm.saving ? 'Đang lưu...' : 'Lưu thay đổi'}
							</Button>
						</div>
					</Card>

					<!-- Quick Templates -->
					<div
						class="rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 p-6 text-white shadow-lg"
					>
						<h3 class="mb-2 flex items-center gap-2 text-lg font-bold">⚡ Phân quyền nhanh</h3>
						<p class="mb-4 text-sm text-white/90">
							Chọn mẫu quyền phổ biến để gán nhanh cho vai trò này
						</p>
						<div class="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">
							{#each Object.entries(vm.permissionTemplates) as [key, template] (key)}
								<button
									class="rounded-lg border border-white/20 bg-white/10 p-3 text-left backdrop-blur-sm transition-all hover:bg-white/20 active:scale-95"
									onclick={() => vm.applyTemplate(key as keyof typeof vm.permissionTemplates)}
								>
									<div class="mb-1 text-sm font-semibold">{template.name}</div>
									<div class="line-clamp-2 text-xs text-white/80">{template.description}</div>
								</button>
							{/each}
						</div>
					</div>

					<!-- Permissions Grid -->
					<div class="grid gap-6">
						{#each Object.entries(vm.permissionsByModule) as [moduleName, permissions] (moduleName)}
							<Card>
								<div class="mb-4 flex items-center justify-between border-b pb-3">
									<button
										class="-ml-2 flex items-center gap-3 rounded-lg p-2 transition-colors hover:bg-gray-50"
										onclick={() => vm.toggleModule(moduleName)}
									>
										<div
											class="flex h-5 w-5 items-center justify-center rounded border {vm.isModuleFullySelected(
												moduleName
											)
												? 'border-indigo-600 bg-indigo-600 text-white'
												: 'border-gray-300 text-transparent'}"
										>
											✓
										</div>
										<span class="text-lg font-semibold text-gray-800 capitalize">{moduleName}</span>
									</button>
									<span
										class="rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-600"
									>
										{vm.getModuleProgress(moduleName)}
									</span>
								</div>

								<div class="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
									{#each permissions as permission (permission.id)}
										<label
											class="group flex cursor-pointer items-start gap-3 rounded-lg border border-gray-100 p-3 transition-colors hover:bg-gray-50"
										>
											<input
												type="checkbox"
												checked={vm.rolePermissionIds.includes(permission.id)}
												onchange={() => vm.togglePermission(permission.id)}
												class="mt-1 h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
											/>
											<div>
												<div
													class="font-medium text-gray-900 transition-colors group-hover:text-indigo-700"
												>
													{permission.name}
												</div>
												<div class="mt-0.5 font-mono text-xs text-gray-400">
													{permission.code}
												</div>
											</div>
										</label>
									{/each}
								</div>
							</Card>
						{/each}
					</div>
				</div>
			{:else}
				<div
					class="flex flex-col items-center justify-center rounded-xl border-2 border-dashed border-gray-200 bg-white p-12 text-gray-400"
				>
					<div class="mb-3 text-4xl">👈</div>
					<div class="text-lg">Chọn một vai trò bên trái để bắt đầu phân quyền</div>
				</div>
			{/if}
		</div>
	{/if}
</div>

// foodstore-admin/src/app/admin/employees/role-permissions/page.tsx
"use client"

import * as React from "react"
import { Check, Loader2, Save } from "lucide-react"
import { toast } from "sonner"

import { Breadcrumb, BreadcrumbItem, BreadcrumbList, BreadcrumbPage } from "@/components/ui/breadcrumb"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { SidebarTrigger } from "@/components/ui/sidebar"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"
import { permissionService } from "@/lib/services/permission-service"
import { roleService } from "@/lib/services/role-service"
import type { Permission, Role } from "@/lib/types"

const TEMPLATES: Record<string, string[]> = {
  Admin: ["*"],
  Cashier: ["order.view", "order.create", "order.edit", "payment.process"],
  Kitchen: ["order.view", "order.status.update"],
}

export default function RolePermissionsPage() {
  const [roles, setRoles] = React.useState<Role[]>([])
  const [permissions, setPermissions] = React.useState<Permission[]>([])
  const [selectedRoleId, setSelectedRoleId] = React.useState<string | null>(null)
  const [rolePermissionCodes, setRolePermissionCodes] = React.useState<Set<string>>(new Set())
  const [loading, setLoading] = React.useState(true)
  const [saving, setSaving] = React.useState(false)

  const loadData = React.useCallback(async () => {
    setLoading(true)
    try {
      const [rls, perms] = await Promise.all([roleService.getAll(), permissionService.getAll()])
      setRoles(rls.filter((r) => r.isActive))
      setPermissions(perms)
    } catch { toast.error("Không thể tải dữ liệu") }
    finally { setLoading(false) }
  }, [])

  React.useEffect(() => { loadData() }, [loadData])

  React.useEffect(() => {
    if (!selectedRoleId) return
    permissionService.getRolePermissions(selectedRoleId).then((codes) => {
      setRolePermissionCodes(new Set(codes))
    }).catch(() => toast.error("Không thể tải quyền của vai trò"))
  }, [selectedRoleId])

  const grouped = React.useMemo(() => {
    const map: Record<string, Permission[]> = {}
    permissions.forEach((p) => {
      if (!map[p.module]) map[p.module] = []
      map[p.module].push(p)
    })
    return map
  }, [permissions])

  const togglePermission = (code: string) => {
    setRolePermissionCodes((prev) => {
      const next = new Set(prev)
      if (next.has(code)) next.delete(code)
      else next.add(code)
      return next
    })
  }

  const toggleModule = (modulePerms: Permission[], checked: boolean) => {
    setRolePermissionCodes((prev) => {
      const next = new Set(prev)
      modulePerms.forEach((p) => {
        if (checked) next.add(p.code)
        else next.delete(p.code)
      })
      return next
    })
  }

  const applyTemplate = (templateName: string) => {
    const pattern = TEMPLATES[templateName]
    if (!pattern) return
    const isWildcard = pattern[0] === "*"
    if (isWildcard) {
      setRolePermissionCodes(new Set(permissions.map((p) => p.code)))
    } else {
      const matching = permissions.filter((p) => pattern.includes(p.code))
      setRolePermissionCodes(new Set(matching.map((p) => p.code)))
    }
  }

  const handleSave = async () => {
    if (!selectedRoleId) return
    setSaving(true)
    try {
      await permissionService.updateRolePermissions(selectedRoleId, Array.from(rolePermissionCodes))
      toast.success("Cập nhật quyền thành công")
    } catch { toast.error("Không thể cập nhật quyền") }
    finally { setSaving(false) }
  }

  const protectedRoles = ["root", "customer"]
  const selectedRole = roles.find((r) => r.id === selectedRoleId)
  const isProtected = selectedRole ? protectedRoles.includes(selectedRole.name.toLowerCase()) : false

  return (
    <>
      <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
        <div className="flex items-center gap-2 px-4">
          <SidebarTrigger className="-ml-1" />
          <Separator orientation="vertical" className="mr-2 h-4" />
          <Breadcrumb>
            <BreadcrumbList>
              <BreadcrumbItem><BreadcrumbPage>Phân quyền</BreadcrumbPage></BreadcrumbItem>
            </BreadcrumbList>
          </Breadcrumb>
        </div>
      </header>
      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
        {loading ? (
          <div className="flex flex-1 items-center justify-center">
            <Loader2 className="size-8 animate-spin text-muted-foreground" />
          </div>
        ) : (
          <div className="flex gap-6">
            <div className="w-56 shrink-0 space-y-1">
              <h3 className="mb-3 text-sm font-medium text-muted-foreground">Vai trò</h3>
              {roles.map((r) => (
                <button
                  key={r.id}
                  onClick={() => setSelectedRoleId(r.id)}
                  className={`w-full rounded-lg px-3 py-2 text-left text-sm transition-colors ${selectedRoleId === r.id ? "bg-primary text-primary-foreground" : "hover:bg-muted"}`}
                >
                  {r.name}
                </button>
              ))}
            </div>
            <div className="flex-1">
              {selectedRole ? (
                <div className="space-y-4">
                    <div className="flex items-center justify-between">
                    <div>
                      <h2 className="text-lg font-medium">{selectedRole.name}</h2>
                      <p className="text-sm text-muted-foreground">{selectedRole.description}</p>
                    </div>
                    <div className="flex items-center gap-2">
                      {isProtected && (
                        <span className="text-sm text-muted-foreground">Vai trò hệ thống — không thể chỉnh sửa</span>
                      )}
                      <div className="flex gap-1">
                        {Object.keys(TEMPLATES).map((tpl) => (
                          <Badge key={tpl} variant="outline" className={isProtected ? "pointer-events-none opacity-50" : "cursor-pointer"} onClick={() => applyTemplate(tpl)}>
                            {tpl}
                          </Badge>
                        ))}
                      </div>
                      <Button onClick={handleSave} disabled={saving || isProtected} className="gap-1.5">
                        {saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}
                        Lưu
                      </Button>
                    </div>
                  </div>
                  <Separator />
                  <ScrollArea className="h-[calc(100vh-280px)]">
                    <div className="space-y-6 pr-4">
                      {Object.entries(grouped).map(([module, perms]) => {
                        const allChecked = perms.every((p) => rolePermissionCodes.has(p.code))
                        const someChecked = perms.some((p) => rolePermissionCodes.has(p.code))
                        return (
                          <div key={module}>
                            <div className="flex items-center gap-2 mb-2">
                              <input
                                type="checkbox"
                                checked={allChecked}
                                disabled={isProtected}
                                ref={(el) => { if (el) el.indeterminate = someChecked && !allChecked }}
                                onChange={() => toggleModule(perms, !allChecked)}
                                className="size-4"
                              />
                              <h4 className="text-sm font-medium capitalize">{module}</h4>
                            </div>
                            <div className="grid grid-cols-2 gap-1.5 sm:grid-cols-3 md:grid-cols-4">
                              {perms.map((perm) => {
                                const checked = rolePermissionCodes.has(perm.code)
                                return (
                                  <label
                                    key={perm.code}
                                    onClick={() => { if (!isProtected) togglePermission(perm.code) }}
                                    className={`flex items-center gap-2 rounded-lg border p-2 text-sm transition-colors ${isProtected ? "cursor-default opacity-60" : "cursor-pointer hover:bg-muted"} ${checked ? "border-primary bg-primary/5" : ""}`}
                                  >
                                    <div className={`flex size-4 shrink-0 items-center justify-center rounded-sm ${checked ? "bg-primary text-primary-foreground" : "border"}`}>
                                      {checked && <Check className="size-3" />}
                                    </div>
                                    <div className="min-w-0">
                                      <div className="truncate">{perm.name}</div>
                                      <div className="truncate text-xs text-muted-foreground">{perm.code}</div>
                                    </div>
                                  </label>
                                )
                              })}
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  </ScrollArea>
                </div>
              ) : (
                <div className="flex h-64 items-center justify-center text-muted-foreground">
                  Chọn một vai trò để xem và chỉnh sửa quyền
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </>
  )
}
