// ChipmeoPOS/src/routes/admin/payment-settings/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Button from '$lib/components/Button.svelte';
	import Card from '$lib/components/Card.svelte';
	import Modal from '$lib/components/Modal.svelte';
	import { PaymentSettingsState } from './payment-settings.svelte.js';

	const vm = new PaymentSettingsState();

	onMount(() => {
		vm.init();
	});
</script>

<div class="p-6">
	<div class="mb-6 flex items-center justify-between">
		<div>
			<h1 class="text-2xl font-bold text-gray-900">Quản lý tài khoản thanh toán</h1>
			<p class="text-gray-600">Cấu hình tài khoản nhận tiền QR Code</p>
		</div>
		<Button variant="primary" onclick={() => vm.openCreateDialog()}>+ Thêm tài khoản</Button>
	</div>

	{#if vm.loading}
		<div class="py-12 text-center">
			<div
				class="inline-block h-12 w-12 animate-spin rounded-full border-b-2 border-indigo-600"
			></div>
		</div>
	{:else if vm.settings.length === 0}
		<div class="rounded-lg border-2 border-dashed border-gray-200 bg-white py-12 text-center">
			<p class="mb-4 text-lg text-gray-500">Chưa có tài khoản thanh toán nào</p>
			<Button variant="primary" onclick={() => vm.openCreateDialog()}
				>Thêm tài khoản đầu tiên</Button
			>
		</div>
	{:else}
		<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
			{#each vm.settings as setting (setting.id)}
				<div
					class="relative rounded-xl border border-gray-100 bg-white p-6 shadow-sm transition-shadow hover:shadow-md {setting.isDefault
						? 'bg-indigo-50/50 ring-2 ring-indigo-500'
						: ''}"
				>
					{#if setting.isDefault}
						<div
							class="absolute top-4 right-4 rounded bg-indigo-600 px-2 py-1 text-xs font-bold text-white"
						>
							MẶC ĐỊNH
						</div>
					{/if}

					<div class="mb-4">
						<h3 class="mb-1 text-lg font-bold text-gray-900">{setting.bankName}</h3>
						<div class="space-y-2 text-sm">
							<div class="flex justify-between border-b border-gray-100 pb-1">
								<span class="text-gray-500">Số tài khoản:</span>
								<span class="font-medium text-gray-900">{setting.bankAccount}</span>
							</div>
							<div class="flex justify-between border-b border-gray-100 pb-1">
								<span class="text-gray-500">Chủ tài khoản:</span>
								<span class="font-medium text-gray-900 uppercase"
									>{setting.bankAccountName || 'N/A'}</span
								>
							</div>
							<div class="flex justify-between border-b border-gray-100 pb-1">
								<span class="text-gray-500">Mã ngân hàng:</span>
								<span class="font-medium text-gray-900">{setting.bankId}</span>
							</div>
							<div class="flex justify-between">
								<span class="text-gray-500">Template:</span>
								<span class="font-medium text-gray-900">{setting.template}</span>
							</div>
						</div>
					</div>

					<div class="mt-4 flex flex-wrap gap-2 border-t border-gray-100 pt-4">
						<button
							class="rounded bg-indigo-50 px-3 py-1.5 text-sm font-medium text-indigo-600 transition-colors hover:bg-indigo-100"
							onclick={() => vm.openEditDialog(setting)}
						>
							Sửa
						</button>
						{#if !setting.isDefault}
							<button
								class="rounded bg-gray-100 px-3 py-1.5 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-200"
								onclick={() => vm.toggleDefault(setting)}
							>
								Đặt mặc định
							</button>
							<button
								class="ml-auto rounded bg-red-50 px-3 py-1.5 text-sm font-medium text-red-600 transition-colors hover:bg-red-100"
								onclick={() => vm.deleteSetting(setting.id)}
							>
								Xóa
							</button>
						{/if}
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>

<Modal
	bind:open={vm.showDialog}
	title={vm.editingId ? 'Sửa tài khoản' : 'Thêm tài khoản mới'}
	onClose={() => (vm.showDialog = false)}
>
	<form
		onsubmit={(e) => {
			e.preventDefault();
			vm.handleSave();
		}}
		class="space-y-4"
	>
		<div>
			<label for="bankId" class="mb-1 block text-sm font-medium text-gray-700"
				>Chọn ngân hàng *</label
			>
			<select
				id="bankId"
				bind:value={vm.formData.bankId}
				onchange={() => vm.onBankSelect()}
				required
				class="w-full rounded-lg border px-4 py-2 focus:ring-2 focus:ring-indigo-500"
			>
				<option value="">-- Chọn ngân hàng --</option>
				{#each vm.banks as bank (bank.bin)}
					<option value={bank.bin}>{bank.shortName} - {bank.name}</option>
				{/each}
			</select>
			<p class="mt-1 text-xs text-gray-500">Tên ngân hàng sẽ tự động điền sau khi chọn</p>
		</div>

		<div>
			<label for="bankName" class="mb-1 block text-sm font-medium text-gray-700"
				>Tên ngân hàng</label
			>
			<input
				id="bankName"
				type="text"
				bind:value={vm.formData.bankName}
				readonly
				class="w-full cursor-not-allowed rounded-lg border bg-gray-50 px-4 py-2 text-gray-600"
			/>
		</div>

		<div>
			<label for="bankAccount" class="mb-1 block text-sm font-medium text-gray-700"
				>Số tài khoản</label
			>
			<input
				id="bankAccount"
				type="text"
				bind:value={vm.formData.bankAccount}
				placeholder="VD: 108873756885"
				class="w-full rounded-lg border px-4 py-2 focus:ring-2 focus:ring-indigo-500"
			/>
		</div>

		<div>
			<label for="bankAccountName" class="mb-1 block text-sm font-medium text-gray-700"
				>Chủ tài khoản</label
			>
			<input
				id="bankAccountName"
				type="text"
				bind:value={vm.formData.bankAccountName}
				placeholder="VD: NGUYEN QUOC TUAN"
				class="w-full rounded-lg border px-4 py-2 uppercase focus:ring-2 focus:ring-indigo-500"
			/>
		</div>

		<div>
			<label for="template" class="mb-1 block text-sm font-medium text-gray-700">Template QR</label>
			<select
				id="template"
				bind:value={vm.formData.template}
				class="w-full rounded-lg border px-4 py-2 focus:ring-2 focus:ring-indigo-500"
			>
				<option value="compact">Compact (Nhỏ gọn)</option>
				<option value="compact2">Compact 2 (Nhỏ gọn 2)</option>
				<option value="print">Print (In ấn)</option>
				<option value="qr_only">QR Only (Chỉ mã QR)</option>
			</select>
		</div>

		<div class="flex items-center gap-4 pt-2">
			<label class="flex cursor-pointer items-center gap-2">
				<input
					type="checkbox"
					bind:checked={vm.formData.isActive}
					class="h-4 w-4 rounded text-indigo-600 focus:ring-indigo-500"
				/>
				<span class="text-sm font-medium text-gray-700">Kích hoạt</span>
			</label>

			<label class="flex cursor-pointer items-center gap-2">
				<input
					type="checkbox"
					bind:checked={vm.formData.isDefault}
					class="h-4 w-4 rounded text-indigo-600 focus:ring-indigo-500"
				/>
				<span class="text-sm font-medium text-gray-700">Đặt làm mặc định</span>
			</label>
		</div>

		<div class="mt-4 flex gap-3 border-t pt-4">
			<Button variant="primary" type="submit" fullWidth={true}>
				{vm.editingId ? 'Cập nhật' : 'Thêm tài khoản'}
			</Button>
			<Button variant="secondary" onclick={() => (vm.showDialog = false)} fullWidth={true}
				>Hủy</Button
			>
		</div>
	</form>
</Modal>

// foodstore-admin/src/app/admin/food/payment-settings/page.tsx
"use client"

import * as React from "react"
import { Edit, Plus, Star, Trash2 } from "lucide-react"
import { toast } from "sonner"

import { Breadcrumb, BreadcrumbItem, BreadcrumbList, BreadcrumbPage } from "@/components/ui/breadcrumb"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import { SidebarTrigger } from "@/components/ui/sidebar"
import { Switch } from "@/components/ui/switch"
import { NativeSelect } from "@/components/ui/native-select"
import { CrudSheet } from "@/components/crud-sheet"
import { DeleteConfirmDialog } from "@/components/confirm-dialog"
import { paymentSettingService, type Bank } from "@/lib/services/payment-setting-service"
import type { PaymentSetting, PaymentSettingCreateDto, PaymentSettingUpdateDto } from "@/lib/types"

export default function PaymentSettingsPage() {
  const [data, setData] = React.useState<PaymentSetting[]>([])
  const [banks, setBanks] = React.useState<Bank[]>([])
  const [loading, setLoading] = React.useState(true)
  const [sheetOpen, setSheetOpen] = React.useState(false)
  const [editing, setEditing] = React.useState<PaymentSetting | null>(null)
  const [submitting, setSubmitting] = React.useState(false)
  const [deleteOpen, setDeleteOpen] = React.useState(false)
  const [deleting, setDeleting] = React.useState(false)
  const [deleteTarget, setDeleteTarget] = React.useState<PaymentSetting | null>(null)

  const [formBankId, setFormBankId] = React.useState("")
  const [formBankName, setFormBankName] = React.useState("")
  const [formBankAccount, setFormBankAccount] = React.useState("")
  const [formBankAccountName, setFormBankAccountName] = React.useState("")
  const [formTemplate, setFormTemplate] = React.useState("compact2")
  const [formIsDefault, setFormIsDefault] = React.useState(false)
  const [formIsActive, setFormIsActive] = React.useState(true)

  const loadData = React.useCallback(async () => {
    setLoading(true)
    try {
      const [settings, bks] = await Promise.all([paymentSettingService.getAll(), paymentSettingService.getBanks()])
      setData(settings); setBanks(bks)
    } catch { toast.error("Không thể tải dữ liệu") }
    finally { setLoading(false) }
  }, [])

  React.useEffect(() => { loadData() }, [loadData])

  const resetForm = () => {
    setFormBankId(""); setFormBankName(""); setFormBankAccount(""); setFormBankAccountName("")
    setFormTemplate("compact2"); setFormIsDefault(false); setFormIsActive(true); setEditing(null)
  }

  const openCreate = () => { resetForm(); setSheetOpen(true) }
  const openEdit = (item: PaymentSetting) => {
    setEditing(item)
    setFormBankId(item.bankId); setFormBankName(item.bankName)
    setFormBankAccount(item.bankAccount); setFormBankAccountName(item.bankAccountName ?? "")
    setFormTemplate(item.template); setFormIsDefault(item.isDefault); setFormIsActive(item.isActive)
    setSheetOpen(true)
  }

  const onBankSelect = (bin: string) => {
    const bank = banks.find((b) => b.code === bin)
    if (bank) { setFormBankId(bin); setFormBankName(bank.name) }
  }

  const handleSubmit = async () => {
    if (!formBankId || !formBankAccount || !formBankName) { toast.error("Vui lòng nhập đầy đủ thông tin"); return }
    setSubmitting(true)
    try {
      const base = {
        bankId: formBankId, bankAccount: formBankAccount, bankName: formBankName,
        bankAccountName: formBankAccountName || undefined, template: formTemplate,
        isDefault: formIsDefault, isActive: formIsActive,
      }
      if (editing) {
        await paymentSettingService.update(editing.id, base as PaymentSettingUpdateDto)
        toast.success("Cập nhật tài khoản thành công")
      } else {
        await paymentSettingService.create(base as PaymentSettingCreateDto)
        toast.success("Thêm tài khoản thành công")
      }
      setSheetOpen(false); loadData()
    } catch (e) { toast.error((e as Error).message) }
    finally { setSubmitting(false) }
  }

  const handleSetDefault = async (id: string) => {
    try { await paymentSettingService.setDefault(id); toast.success("Đặt làm mặc định thành công"); loadData() }
    catch { toast.error("Không thể đặt mặc định") }
  }

  const confirmDelete = (item: PaymentSetting) => { setDeleteTarget(item); setDeleteOpen(true) }
  const handleDelete = async () => {
    if (!deleteTarget) return
    setDeleting(true)
    try { await paymentSettingService.delete(deleteTarget.id); toast.success("Xóa tài khoản thành công"); setDeleteOpen(false); loadData() }
    catch { toast.error("Không thể xóa tài khoản") }
    finally { setDeleting(false) }
  }

  return (
    <>
      <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
        <div className="flex items-center gap-2 px-4">
          <SidebarTrigger className="-ml-1" />
          <Separator orientation="vertical" className="mr-2 h-4" />
          <Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbPage>Cài đặt thanh toán</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb>
        </div>
      </header>
      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
        <div className="mb-2 flex items-center justify-between">
          <div>
            <h1 className="text-xl font-bold">Tài khoản thanh toán</h1>
            <p className="text-sm text-muted-foreground">Cấu hình tài khoản nhận tiền QR Code</p>
          </div>
          <Button className="gap-1.5" onClick={openCreate}><Plus className="size-4" />Thêm tài khoản</Button>
        </div>

        {loading ? (
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {Array.from({ length: 3 }).map((_, i) => (
              <div key={i} className="h-52 animate-pulse rounded-xl bg-muted" />
            ))}
          </div>
        ) : data.length === 0 ? (
          <div className="flex flex-col items-center justify-center rounded-xl border-2 border-dashed py-16 text-muted-foreground">
            <p className="mb-4 text-lg">Chưa có tài khoản thanh toán nào</p>
            <Button variant="outline" onClick={openCreate}>Thêm tài khoản đầu tiên</Button>
          </div>
        ) : (
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {data.map((setting) => (
              <div key={setting.id} className={`relative rounded-xl border p-6 shadow-sm transition-shadow hover:shadow-md ${setting.isDefault ? "border-primary/40 bg-primary/5 ring-1 ring-primary/30" : "bg-card"}`}>
                {setting.isDefault && (
                  <div className="absolute right-3 top-3 rounded bg-primary px-2 py-0.5 text-[10px] font-bold text-primary-foreground">MẶC ĐỊNH</div>
                )}
                <div className="mb-4">
                  <h3 className="mb-3 text-lg font-bold">{setting.bankName}</h3>
                  <div className="space-y-1.5 text-sm">
                    <div className="flex justify-between border-b pb-1">
                      <span className="text-muted-foreground">Số tài khoản:</span>
                      <span className="font-medium">{setting.bankAccount}</span>
                    </div>
                    <div className="flex justify-between border-b pb-1">
                      <span className="text-muted-foreground">Chủ tài khoản:</span>
                      <span className="font-medium uppercase">{setting.bankAccountName || "N/A"}</span>
                    </div>
                    <div className="flex justify-between border-b pb-1">
                      <span className="text-muted-foreground">Mã ngân hàng:</span>
                      <span className="font-medium">{setting.bankId}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Template:</span>
                      <span className="font-medium">{setting.template}</span>
                    </div>
                  </div>
                </div>
                <div className="mt-4 flex flex-wrap gap-2 border-t pt-4">
                  <Button variant="outline" size="sm" onClick={() => openEdit(setting)}><Edit className="mr-1 size-3.5" />Sửa</Button>
                  {!setting.isDefault && (
                    <>
                      <Button variant="outline" size="sm" onClick={() => handleSetDefault(setting.id)}><Star className="mr-1 size-3.5" />Mặc định</Button>
                      <Button variant="outline" size="sm" className="ml-auto text-destructive" onClick={() => confirmDelete(setting)}><Trash2 className="mr-1 size-3.5" />Xóa</Button>
                    </>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <CrudSheet open={sheetOpen} onOpenChange={setSheetOpen} title={editing ? "Sửa tài khoản" : "Thêm tài khoản mới"} onSubmit={handleSubmit} submitting={submitting}>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="bankId">Ngân hàng *</Label>
            <NativeSelect className="w-full" value={formBankId} onChange={(e) => onBankSelect(e.target.value)}>
              <option value="">-- Chọn ngân hàng --</option>
              {banks.map((b) => (
                <option key={b.code} value={b.code}>{b.shortName} - {b.name}</option>
              ))}
            </NativeSelect>
            <p className="text-xs text-muted-foreground">Tên ngân hàng sẽ tự động điền sau khi chọn</p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="bankName">Tên ngân hàng</Label>
            <Input id="bankName" value={formBankName} readOnly className="bg-muted" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="bankAccount">Số tài khoản *</Label>
            <Input id="bankAccount" value={formBankAccount} onChange={(e) => setFormBankAccount(e.target.value)} placeholder="VD: 108873756885" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="bankAccountName">Chủ tài khoản</Label>
            <Input id="bankAccountName" value={formBankAccountName} onChange={(e) => setFormBankAccountName(e.target.value.toUpperCase())} placeholder="VD: NGUYEN QUOC TUAN" className="uppercase" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="template">Template QR</Label>
            <NativeSelect className="w-full" value={formTemplate} onChange={(e) => setFormTemplate(e.target.value)}>
              <option value="compact">Compact (Nhỏ gọn)</option>
              <option value="compact2">Compact 2 (Nhỏ gọn 2)</option>
              <option value="print">Print (In ấn)</option>
              <option value="qr_only">QR Only (Chỉ mã QR)</option>
            </NativeSelect>
          </div>
          <div className="flex items-center gap-2">
            <Switch id="isActive" checked={formIsActive} onCheckedChange={setFormIsActive} />
            <Label htmlFor="isActive">Kích hoạt</Label>
          </div>
          <div className="flex items-center gap-2">
            <Switch id="isDefault" checked={formIsDefault} onCheckedChange={setFormIsDefault} />
            <Label htmlFor="isDefault">Đặt làm mặc định</Label>
          </div>
        </div>
      </CrudSheet>

      <DeleteConfirmDialog open={deleteOpen} onOpenChange={setDeleteOpen} onConfirm={handleDelete} loading={deleting} itemName={deleteTarget?.bankName} />
    </>
  )
}
